language: php
sudo: required
services:
  - docker

php:
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

env:
matrix:
    include:
        - php: 7.1
          env: dependencies="--prefer-lowest --prefer-stable"
        - php: 7.1
          env: coverage=on

    allow_failures:
        - php: 7.1
          env: coverage=on

install:
  - docker pull raek/test_ftp
  - docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" raek/test_ftp


before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: always